cars_mockup_data = [
    {
        "brand": "Toyota",
        "model": "Camry",
        "year": 2018,
        "color": "Blue",
        "mileage": 35000.5,
        "offer_price": 20000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Honda",
        "model": "Civic",
        "year": 2017,
        "color": "Red",
        "mileage": 42000.7,
        "offer_price": 18000.0,
        "status": "SOLD",
    },
    {
        "brand": "Ford",
        "model": "Fusion",
        "year": 2019,
        "color": "White",
        "mileage": 25000.3,
        "offer_price": 22000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Chevrolet",
        "model": "Malibu",
        "year": 2016,
        "color": "Silver",
        "mileage": 38000.8,
        "offer_price": 17000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Nissan",
        "model": "Altima",
        "year": 2015,
        "color": "Black",
        "mileage": 55000.2,
        "offer_price": 15000.0,
        "status": "SOLD",
    },
    {
        "brand": "BMW",
        "model": "3 Series",
        "year": 2020,
        "color": "Gray",
        "mileage": 18000.1,
        "offer_price": 30000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Mercedes-Benz",
        "model": "C-Class",
        "year": 2017,
        "color": "White",
        "mileage": 32000.4,
        "offer_price": 28000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Audi",
        "model": "A4",
        "year": 2019,
        "color": "Blue",
        "mileage": 24000.6,
        "offer_price": 32000.0,
        "status": "SOLD",
    },
    {
        "brand": "Tesla",
        "model": "Model S",
        "year": 2018,
        "color": "Red",
        "mileage": 20000.0,
        "offer_price": 60000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Volkswagen",
        "model": "Jetta",
        "year": 2019,
        "color": "Black",
        "mileage": 28000.2,
        "offer_price": 22000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Subaru",
        "model": "Outback",
        "year": 2017,
        "color": "Green",
        "mileage": 30000.9,
        "offer_price": 25000.0,
        "status": "SOLD",
    },
    {
        "brand": "Hyundai",
        "model": "Elantra",
        "year": 2016,
        "color": "Silver",
        "mileage": 40000.3,
        "offer_price": 16000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Kia",
        "model": "Optima",
        "year": 2018,
        "color": "White",
        "mileage": 32000.5,
        "offer_price": 20000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Jeep",
        "model": "Cherokee",
        "year": 2019,
        "color": "Blue",
        "mileage": 22000.7,
        "offer_price": 28000.0,
        "status": "SOLD",
    },
    {
        "brand": "Lexus",
        "model": "RX",
        "year": 2017,
        "color": "Black",
        "mileage": 26000.8,
        "offer_price": 35000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Mazda",
        "model": "CX-5",
        "year": 2020,
        "color": "Red",
        "mileage": 15000.1,
        "offer_price": 24000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Infiniti",
        "model": "Q50",
        "year": 2018,
        "color": "Gray",
        "mileage": 28000.4,
        "offer_price": 30000.0,
        "status": "SOLD",
    },
    {
        "brand": "Volvo",
        "model": "XC60",
        "year": 2019,
        "color": "White",
        "mileage": 21000.6,
        "offer_price": 32000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Porsche",
        "model": "Cayenne",
        "year": 2021,
        "color": "Black",
        "mileage": 12000.9,
        "offer_price": 70000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Land Rover",
        "model": "Range Rover",
        "year": 2020,
        "color": "Blue",
        "mileage": 18000.3,
        "offer_price": 80000.0,
        "status": "SOLD",
    },
    {
        "brand": "Jaguar",
        "model": "F-PACE",
        "year": 2019,
        "color": "Silver",
        "mileage": 25000.5,
        "offer_price": 60000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Ram",
        "model": "1500",
        "year": 2020,
        "color": "Black",
        "mileage": 15000.7,
        "offer_price": 40000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "GMC",
        "model": "Sierra",
        "year": 2018,
        "color": "White",
        "mileage": 30000.8,
        "offer_price": 35000.0,
        "status": "SOLD",
    },
    {
        "brand": "Dodge",
        "model": "Charger",
        "year": 2019,
        "color": "Red",
        "mileage": 22000.1,
        "offer_price": 30000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Buick",
        "model": "Encore",
        "year": 2017,
        "color": "Blue",
        "mileage": 28000.3,
        "offer_price": 22000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Lincoln",
        "model": "Navigator",
        "year": 2018,
        "color": "Black",
        "mileage": 25000.5,
        "offer_price": 70000.0,
        "status": "SOLD",
    },
    {
        "brand": "Cadillac",
        "model": "Escalade",
        "year": 2020,
        "color": "White",
        "mileage": 20000.7,
        "offer_price": 90000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Chrysler",
        "model": "300",
        "year": 2018,
        "color": "Gray",
        "mileage": 28000.9,
        "offer_price": 25000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Acura",
        "model": "MDX",
        "year": 2019,
        "color": "Silver",
        "mileage": 23000.1,
        "offer_price": 35000.0,
        "status": "SOLD",
    },
    {
        "brand": "Fiat",
        "model": "500",
        "year": 2016,
        "color": "Red",
        "mileage": 32000.3,
        "offer_price": 15000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Mitsubishi",
        "model": "Outlander",
        "year": 2017,
        "color": "Blue",
        "mileage": 26000.5,
        "offer_price": 20000.0,
        "status": "ACTIVE",
    },
    {
        "brand": "Smart",
        "model": "Fortwo",
        "year": 2018,
        "color": "Black",
        "mileage": 21000.7,
        "offer_price": 18000.0,
        "status": "SOLD",
    },
    {
        "brand": "Mini",
        "model": "Cooper",
        "year": 2019,
        "color": "White",
        "mileage": 24000.9,
        "offer_price": 28000.0,
        "status": "INACTIVE",
    },
    {
        "brand": "Genesis",
        "model": "G70",
        "year": 2020,
        "color": "Silver",
        "mileage": 18000.1,
        "offer_price": 35000.0,
        "status": "ACTIVE",
    },
]
